name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - --version 1.1.12
      - name: Install dependencies
        run: $HOME/.poetry/bin/poetry install
      - name: Run flake8
        run: $HOME/.poetry/bin/poetry run flake8 --ignore=W503
      - name: Run unittests
        run: $HOME/.poetry/bin/poetry run python tests.py
