name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: $HOME/.local/bin/poetry install
      - name: Run flake8
        run: $HOME/.local/bin/poetry run flake8 --ignore=W503
      - name: Run unittests
        run: $HOME/.local/bin/poetry run python tests.py
